### ISSUE TITLE
Cannot override an existing "ext" with package.json config

### ISSUE THREAD

**Issue by matthewp** [stealjs/steal-npm#185]
@dylanrtt commented on [Tue May 19 2015](https://github.com/stealjs/steal/issues/426)

Using the bower.json config, I am able to force the "mustache" file extension use the "stache" renderer, but this no longer works when I switch to package.json. Instead, it simply uses mustache renderer, or at least I'm assuming it's using mustache since mustache helpers work and stache helpers don't.

```js
"ext": {
  "mustache": "can/view/stache/system"
}
```

I can only get it to work with file extensions that have not already been defined such as "foo.stache!bar"  if I define "bar". Since "mustache" is already defined in the canjs package.json, that may be why my config above has no effect.

Yes, I could just rename all of my *.mustache files and references to *.stache, but there are 356 of them and I would rather not deal with the conflicts of my coworkers and feature branches at this time.

---

@matthewp commented on [Tue May 19 2015](https://github.com/stealjs/steal/issues/426#issuecomment-103479802)

Thanks for reporting, probably the issue is that your configuration is applied first, then dependent package's configuration.  I'll look into what is needed to fix this.

---

@ccummings commented on [Mon Jun 08 2015](https://github.com/stealjs/steal/issues/426#issuecomment-109876118)

+1 I just encountered this myself while trying to specify a different handler for stache files.

I traced it to [L296](https://github.com/stealjs/steal/blob/master/ext/npm.js#L296) of the npm extension. There, any package with a system config will overwrite any previous system config.

My project's package.json is read first which sets `ext.stache` but then can's is read and my config is blown away.

---

@matthewp commented on [Mon Jun 08 2015](https://github.com/stealjs/steal/issues/426#issuecomment-109995839)

Yeah, I think we need to use unshift instead of push here: https://github.com/stealjs/steal/blob/master/ext/npm.js#L53

That would cause the packages to be translated in the correct order (i think).

**Comment by matthewp** [comment]
Fixed by #186

**Comment by donkeybanana** [comment]
Sorry to bump this issue, but I can currently reproduce the issue with `steal@1.5.13` using the following `package.json`:

```
{
  "name": "steal-ext-override",
  "version": "1.0.0",
  "description": "https://github.com/stealjs/steal-npm/issues/185",
  "main": "index.js",
  "steal": {
    "ext": {
      "ejs": "can-ejs"
    }
  },
  "devDependencies": {
    "can-ejs": "^3.1.5",
    "steal": "^1.5.13"
  }
}
```

In the browser:

```
> steal.config('ext')['ejs']
< "./src/system.js"
```

**Comment by donkeybanana** [comment]
I noticed this repo is deprecated; follow-up comment is on the original issue at https://github.com/stealjs/steal/issues/426#issuecomment-326804512.
