### ISSUE TITLE
Progressively loaded package.jsons that happen only in the Build loader are not applied to the Local loader

### ISSUE THREAD

**Issue by matthewp** [stealjs/steal-npm#200]
During the build we have 2 loaders, one for plugins and one (called the "local" loader) to trace the main application.  If we progressively load package.jsons on the plugin side, their configuration is not moved over to the local loader side, which is the one that winds up in the production build.

**Comment by justinbmeyer** [comment]
Interesting. So a merge happens. I assume that eventually there is a possibility for conflicts. Once an ext is set, it shouldn't be allowed to change again. 

This might be possible by defining a setter on the first set that throws an error.

**Comment by matthewp** [comment]
Possibly, but that is a different issue. This issue is that configuration which only exists in the pluginLoader doesn't get applied to the localLoader and therefore doesn't wind up in the production build.

**Comment by matthewp** [comment]
Fixed in major
