### ISSUE TITLE
Colab?

### ISSUE THREAD

**Issue by alexisvincent** [stealjs/steal-npm#205]
Hi there, I wonder if theres an opportunity for collaboration here. Have you seen: [systemjs-config-builder](https://github.com/alexisvincent/systemjs-config-builder)

**Comment by matthewp** [comment]
Probably not, for a variety of reasons:

* This project doesn't work with current SystemJS, it only works with an older version. We forked at 0.17 iirc.  No plans to support SystemJS again.
* Our projects take a different approach, this one resolves dependencies in the client and yours seems to generate a config file as a cli tool. If I were to start from scratch I would probably take your approach, or something similar.

Cool project though!

**Comment by justinbmeyer** [comment]
The systemjs fork is the biggest problem. I wonder if there's still some way to share core utilities.

**Comment by alexisvincent** [comment]
Why the fork? Don't you plan to follow SystemJS at all?

**Comment by matthewp** [comment]
See [this thread](https://github.com/stealjs/steal/issues/750) if you want some background as to why we don't use SystemJS. To answer you directly, we (or at least I) do not plan to follow SystemJS at all.

**Comment by alexisvincent** [comment]
Got it, thanks. I understand the motivation, as much as it's a loss for the SystemJS community loosing your feedback.
