### ISSUE TITLE
Meta configuration is not applied for progressively loaded modules

### ISSUE THREAD

**Issue by matthewp** [stealjs/steal-npm#225]
Configuration that is applied for progressively loaded modules is not set on the module `load.metadata` property, which breaks the meta plugin's expectations.

I think this can likely be confirmed by having an npm dependency that depends on a global.

**Comment by matthewp** [comment]
@m-mujica is going to write up a test that demonstrates this.

**Comment by matthewp** [comment]
Adding a large estimate as this is potentially a hard one to solve.

**Comment by m-mujica** [comment]
Branch with the test https://github.com/stealjs/steal-npm/tree/meta-config

**Comment by matthewp** [comment]
Couldn't recreate.
